---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12
#  solo_rb:
#       verify_api_cert: true
#      ssl_verify_mode: verify_peer

platforms:
  - name: debian-7.2.0
    driver:
      box: fgrehm/wheezy64-lxc
      provider: lxc
  - name: debian-8.3.0
    driver:
      box: jessie64-lxc
      provider: lxc
  - name: debian-9
    driver:
      box: stretch64-lxc
      provider: lxc
  - name: ubuntu-14.04
    driver:
      box: fgrehm/trusty64-lxc
      provider: lxc
      synced_folders:
        - [ '.', '/home/vagrant/cookbook']
  - name: ubuntu-16.04
    driver:
      box: xenial64-lxc
      provider: lxc

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[apache2]
      - recipe[php]
      - recipe[phpmyadmin]  
    attributes:
      phpmyadmin:
        fpm: false
      chef-vault:
        databag_fallback: true
      #      rebsoc:
      #  ssl_certificate:
      #    source: 'data-bag'
